name: Build Vue
on: 
  push :
    branches :
      - lab9
      - main
  workflow_dispatch:

jobs:
  build :
    name: build
    runs-on: ubuntu-latest
    steps:
    - name : checkout
      uses: actions/checkout@v2
    - name: install pnpm
      run : |
        curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
        pnpm config set store-dir .pnpm-store
    - name : setup
      uses: actions/setup-node@v2.5.2
    - name: build
      run : |
        pnpm install
        pnpm run build    
        
    - name : artifacts 
      uses : actions/upload-artifact@v3
      with:
        name: artifact-build
        path: dist/
    - name : cache
      uses: actions/cache/save@v3
      with:
        path: |
          node_modules/
        
        
  test :
    if: github.event_name == 'pull_request'
    name : test
    needs : build
    runs-on: ubuntu-latest
    steps: 
    - name : static analysis
      run : |
        echo "pnpm type-check"
        echo "pnpm eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore"
    - name : test
      run: |
        echo "pnpm vitest"
        
  deploy :
    name : deploy
    needs : build 
    runs-on: ubuntu-latest
    steps: 
    - name : download artifact
      uses: actions/download-artifact@v2.1.1
      with : 
        name : artifact-build
        path : ${{github.workspace}} 
    - name : deploy qa
      uses: Azure/static-web-apps-deploy@v1
      with:
        skip_app_build: true
        action: upload 
        azure_static_web_apps_api_token: ${{ secrets.AZURE_QA_DEPLOY_TOKEN }}
        app_artifact_location: ${{github.workspace}} 
        
        
    
        
        
    
        
  
      
    
  
  
