name: Build Vue
on: 
  push :
    branches :
      - lab9
      - main
jobs:
  build :
    runs-on: ubuntu-latest
    steps:
    - name : checkout
      uses: actions/checkout@v2
    - name: before_script
      run : curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - run : pnpm config set store-dir .pnpm-store
    - name: install
      run : pnpm install
    - name: build
      run: pnpm run build
  
  
