name: Build Vue
on: 
  push :
    branches :
      - lab9
      - main
jobs:
  build :
    runs-on: ubuntu-latest
    steps:
    - name : checkout
    - uses: actions/checkout@v2
    - name: install
    - run : pnpm install
    - name: build
    - run: pnpm run build
  
  
