name: Build Vue
on: 
  push :
    branches :
      - lab9
      - main
jobs:
  build-job :
    runs-on: ubuntu-latest
    steps:
    - name : checkout
      uses: actions/checkout@v2
    - name: build
      run : |
        curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
        pnpm config set store-dir .pnpm-store
        pnpm install
        pnpm run build
    - name : artifacts 
      uses : actions/upload-artifact@v3
      with:
        name: artifact-build
        path: dist/
      
    
  
  
